name: Discord Bot Runner

on:
  workflow_dispatch:

# ESTA ES LA MAGIA: Si entra una nueva petición, mata el bot anterior y levanta uno fresco
concurrency:
  group: bot-instancia-unica
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    # Forzamos el límite máximo de GitHub Actions
    timeout-minutes: 360

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Una sola instalación con todas las librerías necesarias
      - name: Instalar dependencias
        run: pip install discord.py boto3 python-dotenv requests duckduckgo-search

      - name: Ejecutar el Bot (Maratón de 6 horas)
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "Iniciando el bot. Escuchando a Discord..."
          python python-bot.py
